### ISSUE TITLE
Measurement operations in the final circuit

### ISSUE THREAD

**Issue by YunJ1e** [cda-tum/qmap#102]
The final circuit always comes with the measurement operations at the end. Is that possible to remove or not-add the measurement?

Thanks

**Comment by burgholzer** [comment]
Hi 👋🏻

Measurements are important for ensuring that the correct circuit is produced after mapping (otherwise you would not know where qubits end up at the end of the circuit).

What I could easily and quickly implement is an option `include_measurements` for the `qmap.compile` function. The default for that would be `true`, but you could disable it if you want to.
Would that suit your needs?

**Comment by burgholzer** [comment]
I created a corresponding PR (#103). If you are satisfied with that solution, I'll merge and release a new version to PyPI.

**Comment by YunJ1e** [comment]
That is nice, and thanks for your help. :)

Best,
Yunjie
