### ISSUE TITLE
qft_10 and qft_16 optimize to the identity

### ISSUE THREAD

**Issue by khieta** [cda-tum/qmap#85]
Hi, I was using the files in your `examples/` directory for my own testing and I noticed that `qft_10.qasm` and `qft_16.qasm` both optimize to the identity circuit using basic rewrite rules. This may be what you intended, but I thought I'd let you know in case it's a bug.

**Comment by burgholzer** [comment]
Hi and sorry for the late reply 👋🏼 
Thanks for bringing this to our attention. We are aware of that. 
However, since these benchmarks have been used quite a lot in the past by various research papers, we never dared to modify them. In the end, they still constitute valid benchmarks for quantum circuit mapping. 
For these reasons, we'd rather keep the benchmarks as they are.
